architectury {
    common(rootProject.enabled_platforms.split(","))
}

loom {
    accessWidenerPath = file("src/main/resources/veritas.accesswidener")
}

dependencies {
    // Keep loader only for compile-time annotations in common code.
    modCompileOnly "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    modApi("net.threetag:palladium-common:${rootProject.palladium_version}") {
        exclude group: "net.fabricmc", module: "fabric-loader"
        exclude group: "net.fabricmc", module: "sponge-mixin"
    }
}

publishing {
    publications {
        mavenCommon(MavenPublication) {
            artifactId = rootProject.archives_base_name
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
    }
}
